dump_base_url: https://dumps.wikimedia.org/kiwix/zim/wikipedia
kafka_broker:
  - localhost:9092
kafka_topic: wikipedia-pages
work_dir: ./data
status_file: ./data/status.log
sink: kafka
http_addr: :8080
