// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: proto/page.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Page struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcUrl        string                 `protobuf:"bytes,1,opt,name=src_url,json=srcUrl,proto3" json:"src_url,omitempty"`
	HttpCode      uint32                 `protobuf:"varint,2,opt,name=http_code,json=httpCode,proto3" json:"http_code,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Content       []byte                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Ip            uint32                 `protobuf:"varint,5,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Page) Reset() {
	*x = Page{}
	mi := &file_proto_page_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_proto_page_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_proto_page_proto_rawDescGZIP(), []int{0}
}

func (x *Page) GetSrcUrl() string {
	if x != nil {
		return x.SrcUrl
	}
	return ""
}

func (x *Page) GetHttpCode() uint32 {
	if x != nil {
		return x.HttpCode
	}
	return 0
}

func (x *Page) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Page) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Page) GetIp() uint32 {
	if x != nil {
		return x.Ip
	}
	return 0
}

var File_proto_page_proto protoreflect.FileDescriptor

const file_proto_page_proto_rawDesc = "" +
	"\n" +
	"\x10proto/page.proto\x12\twikipedia\"\xda\x01\n" +
	"\x04Page\x12\x17\n" +
	"\asrc_url\x18\x01 \x01(\tR\x06srcUrl\x12\x1b\n" +
	"\thttp_code\x18\x02 \x01(\rR\bhttpCode\x126\n" +
	"\aheaders\x18\x03 \x03(\v2\x1c.wikipedia.Page.HeadersEntryR\aheaders\x12\x18\n" +
	"\acontent\x18\x04 \x01(\fR\acontent\x12\x0e\n" +
	"\x02ip\x18\x05 \x01(\rR\x02ip\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B1Z/github.com/example/wikipedia-parser/internal/pbb\x06proto3"

var (
	file_proto_page_proto_rawDescOnce sync.Once
	file_proto_page_proto_rawDescData []byte
)

func file_proto_page_proto_rawDescGZIP() []byte {
	file_proto_page_proto_rawDescOnce.Do(func() {
		file_proto_page_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_page_proto_rawDesc), len(file_proto_page_proto_rawDesc)))
	})
	return file_proto_page_proto_rawDescData
}

var file_proto_page_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_page_proto_goTypes = []any{
	(*Page)(nil), // 0: wikipedia.Page
	nil,          // 1: wikipedia.Page.HeadersEntry
}
var file_proto_page_proto_depIdxs = []int32{
	1, // 0: wikipedia.Page.headers:type_name -> wikipedia.Page.HeadersEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_page_proto_init() }
func file_proto_page_proto_init() {
	if File_proto_page_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_page_proto_rawDesc), len(file_proto_page_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_page_proto_goTypes,
		DependencyIndexes: file_proto_page_proto_depIdxs,
		MessageInfos:      file_proto_page_proto_msgTypes,
	}.Build()
	File_proto_page_proto = out.File
	file_proto_page_proto_goTypes = nil
	file_proto_page_proto_depIdxs = nil
}
